name: ValourIntegration
version: '${project.version}'
main: xyz.skyjoshua.valourIntegration.ValourIntegration
api-version: '${minecraft.version}'
authors: [ SkyJoshua ]
description: Integration between Valour.gg and Minecraft!
website: https://skyjoshua.xyz
softdepend:
  - PremiumVanish