name: ValourIntegration
version: '1.0'
main: xyz.skyjoshua.valourIntegration.ValourIntegration
api-version: '1.21'
authors: [ SkyJoshua, Appocryptha ]
description: Core mod for Liminal based things
website: https://skyjoshua.xyz
